---
title: "My tidying"
author: "gd"
date: "24/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Attach packages
library(tidyverse)
library(janitor)
library(here)
library(readxl)
```

```{r}
inverts <- read_excel(here('data', 'inverts.xlsx'))
```

```{r}
View(inverts)
names(inverts)
summary(inverts)
```

```{r}
inverts_long <- pivot_longer(data = inverts, 
                                    cols = '2016':'2018',
                                    names_to = "year",
                                    values_to = "sp_count")
```

```{r}
inverts_long <- inverts_long %>%
  mutate(year = as.numeric(year))
```

```{r}
inverts_wide <- pivot_wider(data = inverts_long, 
                            names_from = common_name,
                            values_from = sp_count)
```


```{r}
inverts_wide <- inverts_wide %>%
  clean_names()
```

```{r}
inverts_unite <- inverts_wide %>%
  unite(col = site_year,
        c(site, year),
        sep = "_")
```

```{r}
inverts_moyr <- inverts_long %>%
  unite(col = mo_yr,
        c(month, year),
        sep = "/")
```

```{r}
inverts_moyr <- inverts_long %>%
    unite(col = mo_yr,
        c(month, year),
        sep = "hello!")
```

```{r}
inverts_triple_unite <- inverts_long %>%
  unite(col = site_name_year,
        c(site, common_name, year),
        sep = "_")
```

```{r}
inverts_sep <- inverts_unite %>% 
  tidyr::separate(site_year, into = c("my_site", "my_year"))
```

```{r}
ca_abbr <- inverts %>% 
  mutate(
    common_name = 
      str_replace(common_name, 
              pattern = "california", 
              replacement = "CA")
  )
```

