---
title: "lobsters"
author: "gd"
date: "23/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) # install.packages('skimr')
library(kableExtra) # install.packages('kableExtra')
```

```{r}
## read in data
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)
```

```{r}
# explore data
skimr::skim(lobsters) 
```

```{r}
lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm, na.rm = T),
            sd_size_mm =sd(size_mm, na.rm = T),
            median_size_mm = median(size_mm, na.rm = T))
```

```{r}
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm, na.rm = T),
            sd_size_mm =sd(size_mm, na.rm = T),
            median_size_mm = median(size_mm, na.rm = T))
```

```{r}
## `summarise()` regrouping output by 'site' (override with `.groups` argument)
```

```{r}
## inspect our new variable 
siteyear_summary 
```

```{r}
## make a table with our new variable
siteyear_summary %>%
  kable()
```



There are `r nrow(lobsters)` total lobsters included in this report.

```{r}
##ggplot
ggplot(data=siteyear_summary, aes(x=year, y=median_size_mm, color = site)) +
  geom_line()
```

```{r}
ggsave(here('figures','lobsters-line.png'))
```


```{r}
lobsters %>%
  count(site, year)
```

There are `r count(lobsters)` total lobsters included in this summary.


```{r}
lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm/1000,
         millenia = 2000,
         observer = "Girolamo D'Anneo")
```

```{r}
lobsters_detailed %>%
  select(date, site, size_m)
```

