---
title: "Creating graphs in R with `ggplot2`"
author: "gd"
date: "23/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(here)
```

```{r}
ca_np <- read_csv(here("data", "ca_np.csv"))
```

```{r}
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```


```{r}
ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()
```

```{r}
gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))
```

```{r}
gg_base +
  geom_point()
```

```{r}
gg_base +
  geom_col()
```

```{r}
gg_base +
  geom_area()
```

```{r}
ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line(
    color = "green1",
    linetype = "dashed"
  )
```

```{r}
gg_base +
  geom_point(color = "purple",
             pch = 17,
             size = 4,
             alpha = 0.5)
```

```{r}
gg_base +
  geom_area(color='red',
            alpha=0.2)
```

```{r}
gg_base + 
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  )
```

```{r}
gg_base + 
  geom_col(aes(fill = visitors))
```

```{r}
gg_base +
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  ) +
  theme_bw()
```

```{r}
gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Anni",
    y = "Visitatori annuali dei Parchi",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  )
```

```{r}
ggplot(data = ca_np, aes(x = year, y = visitors)) +
  geom_line(aes(color=park_name))
```

```{r}
gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))
```

```{r}
gg_np +
  geom_line(show.legend = FALSE, color='green') +
  theme_light() + 
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)
```

```{r}
ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)
```

